/* password is de username beginnend met een hoofdletter, met 123! eraan vast e.g.: username: robbert, password: Robbert123! */
INSERT INTO users (username, password, enabled)
VALUES ('robbert', '$2a$10$3Ir/NL1.eapVLyq3NCCLfOyIsq.9y7ZziVJWs9hD4ChDlLNTV08mu', TRUE),
       ('anna', '$2a$10$C/gQ5s2z3Uu2qfnl99KnsuFpNbUand CTpafb0seJMuJC052k5wan2eam', TRUE),
       ('cor', '$2a$10$QU/ld5fuW0VspXD8wSbWV.WwIVzko4sVQiZKwqmw6Inj2pr4XrwyO', TRUE),
       ('dirk', '$2a$10$EfOSvkOuW7bvg2fMHeosHO.1RU6vkuC4jBkDfgfH26zK6KxmdNuZq', TRUE),
       ('rosalie', '$2a$10$TCrY0AuuhxIfqN4e2Oxv5u2pQAH129PsvEXJFty4Ag/lxmZzZE8h6', TRUE),
       ('admin', '$2a$10$Nr3hVx0Y2nf0aQykOA1UuuDPLp9rU.dRVEK0FMw2W5rS6AsxjOwKy', TRUE);

INSERT INTO authorities (username, authority)
VALUES ('robbert', 'ROLE_STUDENT'),
       ('anna', 'ROLE_STUDENT'),
       ('cor', 'ROLE_STUDENT'),
       ('dirk', 'ROLE_TEACHER'),
       ('rosalie', 'ROLE_TEACHER'),
       ('admin', 'ROLE_ADMIN');

INSERT INTO teachers (name, email, age, residence, phone_number, instruments, description, experience, preference_for_lesson_type)
VALUES ('Dirk', 'dirk@gmail.com', '29', 'Rotterdam', '0645678912', 'guitar',
        'Quisque eget arcu nibh. Donec egestas leo turpis, quis facilisis ante elementum at. Vestibulum iaculis finibus volutpat. Mauris ut viverra orci. Vestibulum scelerisque velit non.',
        'Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur nisi sem, condimentum sit amet facilisis sed, aliquet sed ligula. Vivamus pharetra dignissim velit, vel convallis leo finibus vel. Ut mollis lorem vitae justo bibendum tincidunt. Nullam nec dui at urna.',
        'Videolessen'),
       ('Rosalie', 'rosalie@gmail.com', '35', 'Breda', '0698732165', 'keyboard',
        'Duis luctus pulvinar mauris quis facilisis. Etiam hendrerit nulla eget feugiat mattis. Morbi aliquam ipsum.',
        'Suspendisse potenti. Duis eget sem vitae elit egestas semper. Curabitur dapibus blandit leo, et dapibus nulla. Cras nec leo fermentum, pellentesque mauris id, placerat odio. Ut vitae odio quis lorem maximus molestie. Ut sodales dolor eu libero iaculis consectetur. Vestibulum eleifend, lectus laoreet congue dapibus, ligula odio fringilla ligula, at.',
        'Les aan huis'),
       ('Loyd', 'loyd@gmail.com', '46', 'Amersfoort', '0664267916', 'guitar',
        'Donec scelerisque tempus consectetur. Proin convallis est eu augue facilisis tempus. Cras ac mi orci. Maecenas sed posuere augue. Aliquam',
        'Curabitur luctus pretium sem ultricies aliquet. Donec lacinia condimentum hendrerit. Aliquam gravida a erat volutpat ornare. Vestibulum justo nisl, rhoncus malesuada consectetur vehicula, luctus a lectus. Maecenas elementum lacus in risus maximus elementum. Duis ex mauris, euismod eget gravida in.',
        'Les aan huis'),
       ('Zaiden', 'zayden@gmail.com', '27', 'Groningen', '0654326782', 'drums',
        'Vestibulum non nisl ex. Nunc in purus non mi commodo viverra vel sed metus. Ut vulputate sapien eget blandit tincidunt.',
        'Nulla facilisi. Ut nec neque at libero semper fringilla. Pellentesque sed pretium ipsum. Sed vel accumsan nisl. Praesent mattis dui ac justo accumsan, id dapibus tellus dapibus. Cras id velit ligula. Vestibulum sodales consequat magna eget eleifend. Pellentesque nec feugiat.',
        'Les aan huis'),
       ('Bonnie', 'bonnie@gmail.com', '37', 'Overijssel', '0613497658', 'singing',
        'Donec scelerisque justo velit, blandit dapibus risus pellentesque sit amet. Nam lacinia ultricies pharetra. Integer porttitor sem massa, a eleifend.',
        'Phasellus et sem turpis. Nullam et tincidunt lacus. Morbi eget maximus felis. Morbi suscipit, arcu a pellentesque fermentum, tellus urna dignissim diam, et finibus turpis sem ut metus. Cras sollicitudin mi ut efficitur interdum. Donec venenatis lacus id enim ornare.',
        'Les aan huis'),
       ('Dorris', 'dorris@gmail.com', '29', 'Rotterdam', '0654397264', 'singing',
        'Phasellus pretium sem id sem euismod ultrices eu id enim. Sed aliquet non eros at vulputate. Sed eu turpis massa',
        'Duis non erat urna. Duis id nibh diam. Nam eget pharetra erat, vel viverra eros. Donec eu turpis ligula. Duis cursus urna sapien, et euismod nulla auctor at. Lorem ipsum dolor sit amet, consectetur adipiscing elit. In vestibulum ligula enim.',
        'Les aan huis'),
       ('Claud', 'claud@gmail.com', '28', 'Breda', '0613567934', 'drums',
        'Nulla tincidunt nibh ligula, non facilisis purus elementum non. Donec auctor leo a turpis aliquam, in aliquam dui laoreet. Pellentesque rhoncus, elit convallis rutrum egestas.',
        'In ipsum arcu, interdum a eros ac, sodales venenatis erat. In blandit molestie venenatis. Vivamus ultricies nunc in magna lacinia semper. Integer non bibendum velit, id accumsan lacus. Aliquam quam.',
        'Les aan huis'),
       ('Bernard', 'bernard@gmail.com', '52', 'Den Haag', '0623976244', 'piano',
        'Praesent consectetur mattis ante ac tincidunt. Nullam fringilla est et rhoncus ultricies. Quisque turpis arcu, posuere id blandit eget, pharetra vel sapien. Aenean hendrerit tempus massa, a laoreet lacus porttitor quis. Duis imperdiet eget sapien.',
        'Suspendisse eu enim egestas, egestas ligula nec, fringilla ex. Suspendisse eget tincidunt enim. Proin ullamcorper pellentesque lectus eget sodales. Morbi eget scelerisque ipsum, tincidunt porttitor velit. Quisque enim ligula, tincidunt at massa in, porttitor viverra arcu. Nullam finibus, mi sit amet mattis congue, felis quam finibus lectus, consequat elementum est lorem sed turpis. Suspendisse potenti. Aliquam dictum tellus at ligula condimentum vehicula. Donec in magna.',
        'Les aan huis'),
       ('Greet', 'greet@gmail.com', '47', 'Amsterdam', '0654397612', 'singing',
        'Donec in mauris laoreet, aliquam turpis ac, consectetur felis. Donec in maximus ligula, sit amet blandit neque. Pellentesque urna libero, pharetra eu rhoncus sit amet.',
        'Nunc eu tristique mi. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Duis molestie ac quam ut finibus. Curabitur tempor ante sit amet ex finibus, at consectetur tortor auctor. In ac pharetra lectus. Nulla tempor.',
        'Les aan huis'),
       ('Susanna', 'susanna@gmail.com', '19', 'Den Haag', '0695592320', 'bassguitar',
        'Pellentesque laoreet risus non neque porta venenatis. Nulla facilisi. Integer vel nisi convallis, tincidunt ante id, commodo neque. Suspendisse non.',
        'Phasellus interdum gravida nisi non facilisis. Suspendisse ut diam sit amet ipsum tempus malesuada eu porta nisi. Vestibulum auctor tincidunt ipsum, et tincidunt enim imperdiet quis. Sed in efficitur erat, ac finibus ipsum. Maecenas feugiat ipsum vel porta sollicitudin. Nulla ac scelerisque sem. Pellentesque habitant.',
        'Les aan huis'),
       ('Anke', 'anke@gmail.com', '25', 'Breda', '0698732165', 'keyboard',
        'Etiam tincidunt, enim sed eleifend gravida, diam augue consequat est, sollicitudin scelerisque mauris purus vel neque. Etiam cursus mattis fringilla. Maecenas tempus nec magna ut consectetur. Proin mattis risus et.',
        'Proin nisi risus, gravida nec condimentum sit amet, luctus in erat. Sed nec ornare orci. Donec euismod justo ut nibh rutrum sodales. Ut tristique, elit nec facilisis lacinia, risus lectus volutpat magna, eu finibus felis risus quis leo. Duis sollicitudin.',
        'Les aan huis'),
       ('Koos', 'koos@gmail.com', '37', 'Overijssel', '0653433109', 'keyboard',
        'Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer cursus turpis nisl, at pellentesque est volutpat sed. Fusce arcu nisl, pharetra et mi non, eleifend condimentum mauris. Curabitur.',
        'Suspendisse varius sit amet mauris vel sollicitudin. Fusce vehicula est vitae odio dapibus varius. In mollis, metus venenatis convallis dapibus, purus sapien accumsan nisi, sit amet suscipit leo mi ac.',
        'Les aan huis'),
       ('Quinten', 'quinten@gmail.com', '27', 'Rotterdam', '0674340576', 'guitar',
        'Sed imperdiet, ipsum vitae euismod blandit, massa enim ornare risus, eget tempus urna magna sit.',
        'Proin volutpat, lacus nec viverra suscipit, turpis metus pharetra diam, quis feugiat leo velit non ipsum. Nam euismod nisl nunc, vitae bibendum ipsum placerat in. Donec vel porttitor lacus. Cras et dolor eget lectus scelerisque blandit et ac velit. Sed nec neque et ligula sagittis blandit. Pellentesque habitant morbi tristique.',
        'Les aan huis');

INSERT INTO students (name, email, age, residence, phone_number, instrument, request, preference_for_lesson_type)
VALUES ('Robbert', 'robbery@gmail.com', '28', 'Rotterdam', '0655751563', 'guitar',
        'Ik wil graag gitaar leren spelen',
        'Videolessen'),
       ('Bas', 'bas@gmail.com', '16', 'Rotterdam', '0673649120', 'guitar',
        'Ik wil graag gitaar leren spelen',
        'Videolessen'),
       ('Thijs', 'thijs@gmail.com', '23', 'Breda', '0612345678', 'bassguitar', 'Ik wil graag gitaar leren spelen',
        'Les aan huis'),
       ('Anna', 'anna@gmail.com', '23', 'Rotterdam', '0634848422', 'singing',
        'Ik wil graag nog beter zingen',
        'Videolessen'),
       ('Jeroen', 'jerony@gmail.com', '32', 'Capelle aan den IJssel', '0657592833', 'keyboard',
        'Ik wil graag keyboard leren spelen',
        'Les aan huis'),
       ('Cor', 'cor@gmail.com', '48', 'Nieuwerkerk aan den IJssel', '0654654773', 'piano',
        'Ik wil graag klassieke muziek spelen',
        'Videolessen');

INSERT INTO lessons (teacher_id, student_id, active, homework)
VALUES (1, 1, TRUE, 'Voor vandaag heb je nog geen huiswerk. Goed gedaan vanmiddag!'),
       (1, 4, TRUE, 'Lekker bezig vandaag!'),
       (1, 2, FALSE, null),
       (1, 5, FALSE, null),
       (2, 3, TRUE, 'Voor vandaag heb je nog geen huiswerk. Goed gedaan vanmiddag!');
